apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: app-prod
type: Opaque
stringData:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MQ==
  POSTGRES_DB: ZG5hLWFuYWx5emVy
